### ISSUE TITLE
Proposal for Intro to Programming [Integrated Campaign]

### ISSUE THREAD

**Issue by shreyagupta98** [bitprj/devrel#7] opened 2020-05-11 22:05 UTC
<--- The DRI for this issue is the President. They will be responsible for keeping this issue up to date at all times --->
<--- Add this issue into the corresponding IMC Milestone --->

#### President
- [x] Open IMC Issue
- [x] Get Project Manager (announce in channel)
- [x] Get Company sponsor

#### Project Manager
- [x] Create #imc-[title] channel on Slack
- [x] Make announcement on #general channel
- [x] Build team on Slack (3-4 marketing + 3-4 devs)

**Comment by kylebegovich** [comment] 2020-05-13 04:26
Duplicate of #2 ?

**Closed** 2020-06-28 05:36 UTC
Labels: IMC
